### ISSUE TITLE
Installing libs via `composer install --no-dev` fails

### ISSUE THREAD

**Issue by worthwhileindustries** [zfcampus/zf-apigility-skeleton#166]
Cannot `composer install --no-dev`

Fails on this version of `Latest commit 410415a  6 days ago`
```
Fatal error: Uncaught Error: Undefined constant 'Apigility\VERSION' in C:\_worthwhile_src\_BTSYNC\_DEV\PROJECTS\zf-apigility-skeleton\module\Application\view\layout\layout.phtml:32 Stack trace: #0 C:\_worthwhile_src\_BTSYNC\_DEV\PROJECTS\zf-apigility-skeleton\vendor\zendframework\zend-view\src\Renderer\PhpRenderer.php(506): include() #1 C:\_worthwhile_src\_BTSYNC\_DEV\PROJECTS\zf-apigility-skeleton\vendor\zendframework\zend-view\src\View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL) #2 C:\_worthwhile_src\_BTSYNC\_DEV\PROJECTS\zf-apigility-skeleton\vendor\zendframework\zend-mvc\src\View\Http\DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel)) #3 C:\_worthwhile_src\_BTSYNC\_DEV\PROJECTS\zf-apigility-skeleton\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent)) #4 C:\_worthwhile_src\_BTSYNC\_DEV\PROJECTS\zf-apigility-skeleton\vendor\zendframework\zend-eventmanager\src\EventManager.php( in C:\_worthwhile_src\_BTSYNC\_DEV\PROJECTS\zf-apigility-skeleton\module\Application\view\layout\layout.phtml on line 32
```

Also, i get route not matched if i enable development mode, create a rest endpoint, disable development mode, run `composer install --no-dev`

after visiting my test endpoint /test

```
A 404 error occurred
Page not found.
The requested URL could not be matched by routing.

No Exception available
© Copyright 2013 - 2018 by Zend Technologies Ltd.
Apigility version

For more information apigility.org
```

**Comment by worthwhileindustries** [comment]
This makes no sense. With a series of `composer install --no-dev` and `composer install` along with enabling and disabling zf admin at random it works.
